name: fold_tracker
description: Fold Tracker Monorepo
publish_to: "none"

environment:
  sdk: '^3.11.3'

workspace:
  - apps/**
  - packages/**

dev_dependencies:
  melos: ^7.5.0
  very_good_analysis: ^10.2.0

melos:
  scripts:
    install:
      description: Get all dependencies.
      exec: melos bootstrap

    get:
      description: Get all dependencies.
      exec: dart pub get

    fix:
      description: Fix source code.
      exec: dart fix --apply

    format:
      description: Format source code.
      exec: dart format .

    clean:
      description: Clean all packages.
      exec: flutter clean