name: fold_tracker
description: Fold Tracker Monorepo
publish_to: "none"

environment:
  sdk: '^3.11.3'

workspace:
  - apps/mobile
  - packages/core
  - packages/core_ui
  - packages/feature_habit
  - packages/shared

dev_dependencies:
  melos: ^7.5.0
  very_good_analysis: ^10.2.0